# Default values for hpcc-azurelfile.
common:
  mountPrefix: "/var/lib/HPCCSystems"

planes:
- name: dali
  subPath: dalistorage
  size: 1Gi
  category: dali
  #sku: "Standard_LRS"
- name: dll
  subPath: queries # cannot currently be changed
  size: 1Gi
  category: dll
  rwmany: true
  #sku: "Standard_LRS"
- name: sasha
  subPath: sasha
  size: 1Gi
  rwmany: true
  category: sasha
  #sku: "Standard_LRS"
- name: data
  subPath: hpcc-data # cannot currently be changed
  size: 3Gi
  category: data # NB: all "data" planes will be auto mounted by engine components and others that require access to data
  rwmany: true
  #sku: "Standard_LRS"
- name: mydropzone
  subPath: dropzone
  size: 1Gi
  rwmany: true
  category: lz
  #sku: "Standard_LRS"
