# Overrides for http-connect secrets in hpcc.
# NB: The "hpcc-connect-testsecret" should be created before installing the helm chart.

certificates:
  enabled: true
  issuers:
    local:
      name: hpcc-local-issuer
      ## kind can be changed to ClusterIssue to refer to a ClusterIssuer. https://cert-manager.io/docs/reference/api-docs/#cert-manager.io/v1.ClusterIssuer
      kind: Issuer
      ## do not define spec (set spec: null), to reference an Issuer resource that already exists in the cluster
      ## change spec if you'd like to change how certificates get issued... see ## https://cert-manager.io/docs/configuration/#supported-issuer-types
      ## for information on what spec should contain.
      spec:
        ca:
          secretName: hpcc-local-issuer-key-pair
    public:
      name: hpcc-public-issuer
      ## kind can be changed to ClusterIssue to refer to a ClusterIssuer. https://cert-manager.io/docs/reference/api-docs/#cert-manager.io/v1.ClusterIssuer
      kind: Issuer
      ## do not define spec (set spec: null), to reference an Issuer resource that already exists in the cluster
      ## change spec if you'd like to change how certificates get issued... see ## https://cert-manager.io/docs/configuration/#supported-issuer-types
      ## for information on what spec should contain.
      spec:
        selfSigned: {}
    vaultclient:
      name: hpcc-vault-issuer
      enabled: true
      domain: hpcc.example.com
      rolePrefix: "hpcc-"
      kind: Issuer
      spec:
        ca:
          secretName: hpcc-vaultclient-issuer-key-pair

    signing: # intended to be used for signing/verification purposes only, e.g. by dafilesrv
      enabled: false
      name: hpcc-signing-issuer
      ## kind can be changed to ClusterIssue to refer to a ClusterIssuer. https://cert-manager.io/docs/reference/api-docs/#cert-manager.io/v1.ClusterIssuer
      kind: Issuer
      ## do not define spec (set spec: null), to reference an Issuer resource that already exists in the cluster
      ## change spec if you'd like to change how certificates get issued... see ## https://cert-manager.io/docs/configuration/#supported-issuer-types
      ## for information on what spec should contain.
      spec:
        ca:
          secretName: hpcc-signing-issuer-key-pair

vaults:
  ecl:
    - name: my-ecl-vault
      url: https://vault.vaultns:8200/v1/secret/data/ecl/${secret}
      kind: kv-v2
  eclUser:
    - name: my-eclUser-vault
      url: https://vault.vaultns:8200/v1/secret/data/eclUser/${secret}
      kind: kv-v2

